-- Invite codes never expired: a pending pair row lived forever, so a code
-- generated months ago could still be redeemed — including one generated by a
-- user who has since paired with someone else, which silently overwrote that
-- existing relationship.

alter table public.pairs
  add column if not exists expires_at timestamptz;

-- Existing pending invites have no expiry. Backfill from created_at so they
-- land in the past: any code still outstanding is stale by definition, and
-- the redeem path now requires expires_at to be in the future.
update public.pairs
   set expires_at = created_at + interval '15 minutes'
 where status = 'pending'
   and expires_at is null;

-- Redemption looks pairs up by code on every attempt.
create index if not exists pairs_invite_code_idx
  on public.pairs (invite_code)
  where invite_code is not null;
